kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: titangrm-iot
apiVersion: v1
data:
  init-zookeeper.sh: |-
    #!/bin/bash
    set -e
    set -x

    [ -d /zookeeper/data ] || mkdir /zookeeper/data
    [ -d /zookeeper/log ]  || mkdir /zookeeper/log
    [ -z "$ID_OFFSET" ] && ID_OFFSET=1
    export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-} + $ID_OFFSET))
    echo "${ZOOKEEPER_SERVER_ID:-1}" | tee /zookeeper/data/myid
    cp -Lur /etc/zookeeper-configmap/* /conf
    sed -i "s/server\.$ZOOKEEPER_SERVER_ID\=[a-z0-9.-]*/server.$ZOOKEEPER_SERVER_ID=0.0.0.0/" /conf/zoo.cfg

  zoo.cfg: |-
    tickTime=2000
    dataDir=/zookeeper/data
    dataLogDir=/zookeeper/log
    clientPort=2181
    maxClientCnxns=8
    initLimit=5
    syncLimit=2
    server.1=zookeeper-0.zookeeper-server:2888:3888:participant
    server.2=zookeeper-1.zookeeper-server:2888:3888:participant
    server.3=zookeeper-2.zookeeper-server:2888:3888:participant

  log4j.properties: |-
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

    # Suppress connection log messages, three lines per livenessProbe execution
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxnFactory=WARN
    log4j.logger.org.apache.zookeeper.server.NIOServerCnxn=WARN
