apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  namespace: titangrm-iot
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - name: rest
    port: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-server
  namespace: titangrm-iot
spec:
  selector:
    app: elasticsearch
  ports:
  - name: rest
    port: 9200
