apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt
  namespace: titangrm-iot
spec:
  selector:
    matchLabels:
      app: mqtt-broker
  serviceName: "mqtt-broker"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mqtt-broker
        image: titangrm/iot-broker:1.0.0
        env:
        - name: IOT_PROTOCOL
          value: MQTT
        ports:
        - name: plain
          containerPort: 1883
        - name: tls
          containerPort: 8883
        lifecycle:
          preStop:
            exec:
             command: ["sh", "-ce", "kill -s TERM 1; while $(kill -0 1 2>/dev/null); do sleep 1; done"]
        resources:
          requests:
            cpu: 2048m
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 3
          timeoutSeconds: 2
          periodSeconds: 30
