# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: titangrm-iot
spec:
  ports:
  - port: 9092
  # [podname].kafka-broker.titangrm-iot.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: titangrm-iot
spec:
  ports:
  - port: 9092
  selector:
    app: kafka

