# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-brokers
  namespace: titangrm-iot
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: titangrm-iot
spec:
  ports:
  - port: 9092
  selector:
    app: kafka