apiVersion: batch/v1
kind: Job
metadata:
  name: create-connect-topics
  namespace: titangrm-iot
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-connect-topics
    spec:
      containers:
      - name: kafka-broker
        image: titangrm/kafka:2.1.0
        env:
        - name: KAFKA_BROKER_REPLICAS
          value: "3"
        - name: ZOOKEEPER_SERVER
          value: "zookeeper-server:2181/iot-default"
        command: ['/bin/bash', '/kafka-connect/create-connect-topics.sh']
        volumeMounts:
        - name: configmap
          mountPath: /kafka-connect
      volumes:
      - name: configmap
        configMap:
          name: kafka-connect-config
      restartPolicy: Never
